import { ConfigState } from "@/types/configSchema";

// --------------- CLAUDE.md ---------------
export function generateClaudeMd(config: ConfigState): string {
  const { basics, core } = config;
  const postureMap: Record<string, string> = {
    "read-first": "Always read and understand the existing code thoroughly before making any changes.",
    "plan-first": "Always generate a step-by-step plan and share it before executing file modifications.",
    "small-batch": "Make small, focused changes and verify tests pass before each subsequent modification.",
    "aggressive": "Execute changes rapidly in bulk when the intent is clear and tests will validate outcomes.",
  };

  return `# CLAUDE.md — ${basics.projectName}

> This file is the core AI operating manual for this project. Claude reads it at the start of every session.

## Project Overview

**Name:** ${basics.projectName}  
**Type:** ${basics.repoType}  
**Goal:** ${basics.workflowGoal === "new" ? "Building a new project from scratch" : basics.workflowGoal === "reverse" ? "Reverse engineering an existing codebase" : basics.workflowGoal === "refactor" ? "Refactoring and modernising the codebase" : "New development + reverse engineering an existing system"}  
${basics.description ? `**Description:** ${basics.description}` : ""}
${basics.teamName ? `**Team:** ${basics.teamName}` : ""}
**Package Manager:** ${basics.packageManager}
${basics.testingStack ? `**Testing Stack:** ${basics.testingStack}` : ""}

---

## Editing Posture

${postureMap[core.editingPosture]}

${core.editingPosture === "plan-first" ? `Before modifying any file:
1. Summarise what you understand about the existing code
2. Describe what you intend to change and why
3. List the files you will touch
4. Wait for confirmation if unsure
` : ""}

---

## Architecture Guidance

- Respect the folder structure and module boundaries already established.
- Do not introduce new global dependencies without noting the tradeoff.
- Prefer extending existing patterns over inventing new ones.
- When unsure about intent, read more code — don't invent assumptions.

## Coding Standards

- Match the indentation, naming, and style already used in each file.
- Write self-documenting code; add comments only when necessary for non-obvious decisions.
- Keep functions small and single-purpose.
- Handle all error cases explicitly — never swallow exceptions silently.
- Do not leave TODOs or debug statements in committed code.

## Testing Expectations

${basics.testingStack ? `- Testing stack: **${basics.testingStack}**` : "- Use the testing framework already present in the project."}
- Every new function or component should have at least one test.
- Regression bugs must have a corresponding test added before the fix.
- Do not break existing tests. If a test becomes irrelevant, explain why and remove it explicitly.

## Documentation Expectations

- Public functions and complex logic should have inline doc comments.
- Major architectural changes require an ADR in \`docs/decisions/\`.
- Feature additions require a feature spec in \`docs/features/\`.
- Keep \`README.md\` up to date with setup and usage changes.

## Review Expectations

- PRs should be focused (one concern per PR).
- No secrets, tokens, or credentials in any committed file.
- All linting and tests must pass before merge.

## Safe Editing Rules

- Security strictness: **${core.securityStrictness}**
${core.securityStrictness === "high" ? `- NEVER write API keys, tokens, passwords, or secrets to any file.
- NEVER run \`rm -rf\` or destructive filesystem commands.
- NEVER commit \`.env\` files containing real values.
- ALWAYS use environment variable references instead.` : core.securityStrictness === "medium" ? `- Do not write secrets to committed files.
- Use environment variables for all sensitive configuration.
- Warn before running any destructive or irreversible commands.` : `- Use reasonable care with secrets and sensitive data.
- Prefer environment variables for API keys and configuration.`}

---

*Generated by [Claude SDLC Config Generator](https://github.com)*
`;
}

// --------------- AGENTS.md ---------------
export function generateAgentsMd(config: ConfigState, selectedSubagentDefs: any[]): string {
  return `# AGENTS.md — ${config.basics.projectName}

> This file lists available subagents for this project. Claude delegates specific tasks to these specialised AI assistants.

## Overview

This project has ${selectedSubagentDefs.length} configured subagent${selectedSubagentDefs.length !== 1 ? "s" : ""}. 
Each is a focused AI assistant with a defined role, allowed tools, and expected output format.

---

${selectedSubagentDefs.map((agent) => `## ${agent.label}

**Role:** ${agent.role}  
**File:** \`.claude/agents/${agent.id}.md\`

${agent.description}

**Allowed Tools:** ${agent.toolScope.join(", ")}

**When to use:** Invoke this agent when you need focused, reliable execution of ${agent.role.toLowerCase()} tasks without the generalist context.

---
`).join("\n")}
*Generated by Claude SDLC Config Generator*
`;
}

// --------------- README-SETUP.md ---------------
export function generateReadmeSetup(config: ConfigState): string {
  return `# README-SETUP.md — Claude Setup Guide for ${config.basics.projectName}

This folder contains a Claude AI configuration package. Here is how to get started.

## What's Included

\`\`\`
CLAUDE.md           — Core AI operating instructions
AGENTS.md           — Subagent directory and delegation guide
.claude/
  settings.json     — Claude tool permissions
  rules/            — Focused rules files by domain
  skills/           — Workflow skill playbooks with templates
  agents/           — Subagent system prompt definitions
  hooks/            — Automated pre/post tool-use scripts
docs/               — Project documentation templates
${config.obsidian.includeVault ? "obsidian-vault/      — Structured knowledge graph vault" : ""}
\`\`\`

## Quick Start

1. Copy the contents of this zip into the root of your project repository.
2. Open \`CLAUDE.md\` and fill in any project-specific placeholders.
3. If using hooks, make the scripts executable:
   \`\`\`bash
   chmod +x .claude/hooks/*.sh
   \`\`\`
4. Review \`.claude/settings.json\` and adjust permissions as needed.
5. Start a Claude session — it will automatically read \`CLAUDE.md\` and \`AGENTS.md\`.

## Skills Usage

Each skill in \`.claude/skills/\` is a playbook. To invoke a skill, tell Claude:

> "Use the **reverse-engineer** skill to map this codebase."

Claude will follow the structured steps defined in that skill's \`SKILL.md\`.

## Hooks

Hooks run automatically based on Claude's tool events. Files in \`.claude/hooks/\` should be:
- Made executable (\`chmod +x\`)
- Set up in \`.claude/settings.json\` under the \`hooks\` key

## Editing CLAUDE.md

\`CLAUDE.md\` is the single most important file. Keep it updated as the project evolves.  
Think of it as a living onboarding doc for your AI assistant.

---

*For the latest version of this tool, visit the Claude SDLC Config Generator.*
`;
}

// --------------- .claude/settings.json ---------------
export function generateSettingsJson(config: ConfigState, selectedHookDefs: any[]): string {
  const hooks: Record<string, any[]> = {};

  selectedHookDefs.forEach((hook) => {
    const event = hook.event;
    if (!hooks[event]) hooks[event] = [];
    hooks[event].push({
      matcher: "*",
      hooks: [{ type: "command", command: ".claude/hooks/" + hook.filename }],
    });
  });

  const settings: Record<string, any> = {
    permissions: {
      allow: ["Read", "Edit", "Bash(*)"],
      deny:
        config.core.securityStrictness === "high"
          ? ["Bash(rm -rf*)", "Bash(curl * | bash*)", "Bash(npm publish*)"]
          : config.core.securityStrictness === "medium"
          ? ["Bash(rm -rf*)"]
          : [],
    },
  };

  if (Object.keys(hooks).length > 0) {
    settings.hooks = hooks;
  }

  return JSON.stringify(settings, null, 2);
}

// --------------- Rules ---------------
const ruleContent: Record<string, string> = {
  frontend: `# Frontend Rules

- Use the existing component library — do not introduce new UI frameworks.
- Keep components small and single-responsibility.
- Co-locate component tests with the component file.
- Accessibility: every interactive element must have ARIA labels where relevant.
- No inline styles — use the design system tokens.
- State: prefer local state; only lift to global state when truly shared across distant components.
- Images must have alt text. Avoid layout shift with explicit width/height.
`,
  backend: `# Backend Rules

- All endpoints must validate their inputs using the project's validation library.
- Return consistent error shapes: \`{ error: string, code: string }\`.
- Log at appropriate levels: INFO for flow, WARN for recoverable issues, ERROR for exceptions.
- Database queries must use parameterised statements — never concatenate user input into SQL.
- Sensitive fields (passwords, tokens) must never be logged or returned in API responses.
- All async functions must handle rejection explicitly.
`,
  tests: `# Test Rules

- Tests live next to the code they test (e.g. \`foo.test.ts\` beside \`foo.ts\`).
- Unit tests must not hit the network or filesystem — use mocks.
- Integration tests may use a real database/service in an isolated environment.
- Test names must describe the behaviour, not the implementation: \`should return 404 when user not found\`.
- Coverage target: 80% line coverage minimum for new code.
- Failing tests block merge — do not skip or comment out tests without a documented reason.
`,
  docs: `# Documentation Rules

- Every exported function must have a JSDoc comment describing its purpose and parameters.
- Each new feature must have a corresponding entry in \`docs/features/\`.
- Architectural decisions must be captured in \`docs/decisions/\` as ADRs.
- Keep \`README.md\` current: if setup steps change, update them immediately.
- Do not leave placeholder text or "TODO: document this" comments in committed docs.
`,
  security: `# Security Rules

- NEVER hardcode API keys, passwords, or tokens in source code.
- Use environment variables for all secrets — reference \`.env.example\` to show required vars.
- Validate and sanitise all user input before processing or storing.
- Dependencies: review \`npm audit\` findings before merging. Critical vulnerabilities block merge.
- Authentication: never roll your own crypto or auth logic — use proven libraries.
- HTTPS everywhere — no plaintext HTTP calls in production code.
`,
  refactoring: `# Refactoring Rules

- Refactor and feature work belong in separate PRs — never mix them.
- All tests must remain green throughout the refactor.
- Rename with confidence only when search confirms all usages are updated.
- Extract shared logic into utilities — resist copy-paste duplication.
- Delete dead code rather than commenting it out.
- After refactoring, run the full test suite and linter before committing.
`,
  "reverse-engineering": `# Reverse Engineering Rules

- Begin by reading \`CLAUDE.md\`, package manifests, and entry points.
- Map the folder structure before reading individual files.
- Document each module's purpose before diving into implementation details.
- Flag any code that appears security-sensitive, deprecated, or architecturally significant.
- Produce output in \`docs/reverse-engineering/\` using the templates in \`.claude/skills/reverse-engineer/\`.
- Do not modify any source files during a reverse engineering session — read only.
`,
};

export function generateRuleContent(ruleId: string): string {
  return ruleContent[ruleId] ?? `# ${ruleId} Rules\n\nAdd your ${ruleId} rules here.\n`;
}

// --------------- Skills ---------------
const skillContentMap: Record<string, string> = {
  "reverse-engineer": `# Skill: Reverse Engineer

## Purpose
Systematically explore an unknown or inherited codebase to produce structured documentation of its architecture, data models, APIs, and business logic.

## When to Use
- Joining a project with no documentation
- Planning a migration or major refactor
- Auditing a codebase before acquisition or handoff

## Inputs Required
- Access to the full source code
- Package manifests (package.json, requirements.txt, etc.)
- Any existing README or docs

## Step-by-Step Workflow

1. **Orient** — Read \`CLAUDE.md\`, \`README\`, and package manifests. Identify the tech stack and entry points.
2. **Map Folders** — Produce a folder tree and annotate the purpose of each top-level directory.
3. **Identify Modules** — List every major module/package, its responsibility, and its external dependencies.
4. **Trace Data Flows** — Follow the primary data path from input (API, UI, event) to storage.
5. **Document APIs** — List all public API endpoints or interface methods with their signatures.
6. **Map Data Models** — Document entities, schemas, and relationships.
7. **Flag Risks** — Note deprecated code, security concerns, and architectural debt.
8. **Write System Overview** — Produce the \`system-overview.md\` output document.

## Output Format
- \`system-overview.md\` — High-level architecture summary
- \`feature-inventory.md\` — List of features and business rules
- \`api-map.md\` — All API contracts
- \`data-model-map.md\` — Entity relationships

## Checklist
- [ ] Entry point identified
- [ ] Folder tree annotated
- [ ] All modules listed
- [ ] Data models documented
- [ ] APIs mapped
- [ ] Security risks flagged
- [ ] system-overview.md produced
`,
  "write-tests": `# Skill: Write Tests

## Purpose
Generate comprehensive unit, integration, and end-to-end tests aligned to the project's testing stack and coverage goals.

## When to Use
- Adding test coverage to untested code
- Creating tests as part of TDD before implementing a feature
- Writing regression tests after a bug is fixed
- Reviewing and expanding existing test suites

## Inputs Required
- The file or module to test
- The testing framework in use
- Any existing test patterns to follow

## Step-by-Step Workflow

1. **Understand the contract** — Read the function/component and identify inputs, outputs, and side effects.
2. **Run existing tests** — Confirm what's already covered.
3. **Design test cases** — Happy path, edge cases, error states.
4. **Write unit tests** — Pure logic, no I/O, use mocks for dependencies.
5. **Write integration tests** — Test the interaction between real components.
6. **Verify coverage** — Run the coverage reporter and confirm thresholds are met.
7. **Review test quality** — Tests must be readable, isolated, and deterministic.

## Output Format
- Test file co-located with source: \`foo.test.ts\`
- Coverage report summary

## Checklist
- [ ] Happy path covered
- [ ] Error states tested
- [ ] Edge cases handled
- [ ] External dependencies mocked in unit tests
- [ ] Tests run and pass
- [ ] Coverage threshold met
`,
};

export function generateSkillMd(skillId: string, skillLabel: string): string {
  return skillContentMap[skillId] ?? `# Skill: ${skillLabel}

## Purpose
Describe the purpose of this skill.

## When to Use
Describe the situations that call for this skill.

## Inputs Required
- Source files or context needed

## Step-by-Step Workflow

1. Step one
2. Step two
3. Step three

## Output Format
Describe the expected outputs.

## Checklist
- [ ] Step one complete
- [ ] Output produced
`;
}

// --------------- Hooks ---------------
const hookScripts: Record<string, string> = {
  "format.sh": `#!/bin/bash
# Claude PostToolUse Hook: Auto-Format
# Runs after file writes to ensure consistent formatting
set -e

FILE="$CLAUDE_TOOL_INPUT_FILE_PATH"
if [ -z "$FILE" ]; then exit 0; fi

if command -v prettier &>/dev/null; then
  prettier --write "$FILE" 2>/dev/null || true
elif command -v gofmt &>/dev/null && [[ "$FILE" == *.go ]]; then
  gofmt -w "$FILE"
fi
`,
  "lint.sh": `#!/bin/bash
# Claude PostToolUse Hook: Lint Check
# Runs ESLint (or equivalent) on changed files
set -e

FILE="$CLAUDE_TOOL_INPUT_FILE_PATH"
if [ -z "$FILE" ]; then exit 0; fi

if command -v eslint &>/dev/null && [[ "$FILE" == *.ts || "$FILE" == *.tsx || "$FILE" == *.js ]]; then
  eslint "$FILE" --max-warnings 0 || { echo "Lint failed for $FILE"; exit 1; }
fi
`,
  "test-changed.sh": "#!/bin/bash\n# Claude PostToolUse Hook: Test Changed Files\nset -e\n\nFILE=\"$CLAUDE_TOOL_INPUT_FILE_PATH\"\nif [ -z \"$FILE\" ]; then exit 0; fi\n\nTEST_FILE=\"${FILE%.ts}.test.ts\"\nif [ -f \"$TEST_FILE\" ]; then\n  npx jest \"$TEST_FILE\" --passWithNoTests 2>&1 | tail -5\nfi\n",
  "block-secrets.sh": `#!/bin/bash
# Claude PreToolUse Hook: Block Secrets
# Prevents writing files containing common secret patterns
CONTENT="$CLAUDE_TOOL_INPUT_CONTENT"

PATTERNS=(
  "sk-[a-zA-Z0-9]{20,}"
  "AKIA[0-9A-Z]{16}"
  "ghp_[a-zA-Z0-9]{36}"
  "Bearer [a-zA-Z0-9_\\-\\.]{20,}"
  "password\\s*=\\s*['\"][^'\"]{6,}"
)

for pattern in "\${PATTERNS[@]}"; do
  if echo "$CONTENT" | grep -qE "$pattern"; then
    echo "BLOCKED: Detected potential secret in file content. Remove credentials and use env vars."
    exit 2
  fi
done
exit 0
`,
  "block-dangerous.sh": `#!/bin/bash
# Claude PreToolUse Hook: Block Dangerous Commands
COMMAND="$CLAUDE_TOOL_INPUT_COMMAND"

BLOCKED=(
  "rm -rf /"
  "rm -rf ~"
  "curl.*| bash"
  "curl.*| sh"
  "npm publish"
  "git push --force"
)

for pattern in "\${BLOCKED[@]}"; do
  if echo "$COMMAND" | grep -qiE "$pattern"; then
    echo "BLOCKED: Dangerous command pattern detected: $pattern"
    exit 2
  fi
done
exit 0
`,
};

export function generateHookScript(filename: string): string {
  return hookScripts[filename] ?? `#!/bin/bash\n# Hook: ${filename}\necho "Hook executed"\n`;
}

// --------------- Subagents ---------------
const subagentPrompts: Record<string, string> = {
  "reverse-engineer-analyst": `---
name: Reverse Engineer Analyst
description: Explores unknown repositories, maps structure, and produces full documentation of architecture and data flows.
tools:
  - Read
  - Glob
  - Grep
  - Write
---

You are a **Reverse Engineer Analyst** for this project.

## Role
Your job is to systematically explore an unknown or inherited codebase and produce a comprehensive, structured understanding of how it works.

## Goals
1. Map the full folder and module structure.
2. Identify all entry points (CLI, API, event handlers, UI routes).
3. Trace primary data flows from input to storage.
4. Document all public APIs, data models, and entity relationships.
5. Flag deprecated patterns, security concerns, and architectural debt.

## Boundaries
- **DO NOT** modify any source files. This is a read-only exploration mission.
- **DO NOT** install dependencies or run the application.
- **DO** produce all outputs as markdown documents in \`docs/reverse-engineering/\`.

## Output Format
For each exploration session, produce:
- \`system-overview.md\` — Architecture summary
- \`feature-inventory.md\` — Business features and flows
- \`api-map.md\` — All API endpoints
- \`data-model-map.md\` — Entities and relationships
`,
};

export function generateSubagentMd(agentId: string, agentDef: any): string {
  return subagentPrompts[agentId] ?? `---
name: ${agentDef.label}
description: ${agentDef.description}
tools:
  - Read
  - Write
---

# ${agentDef.label}

**Role:** ${agentDef.role}

${agentDef.description}

## Goals
Describe the primary goals for this agent.

## Boundaries
- DO NOT perform actions outside this agent's defined scope.

## Output Format
Describe expected output artifacts.
`;
}

// --------------- Doc Templates ---------------
const docTemplates: Record<string, string> = {
  "brd-template.md": `---
title: "[Feature/Product Name] Business Requirements Document"
version: 1.0
status: Draft
date: YYYY-MM-DD
author: ""
stakeholders: []
---

# Business Requirements Document

## 1. Executive Summary
Provide a 2–3 sentence summary of the business need and proposed solution.

## 2. Problem Statement
Describe the current situation and the problem this initiative solves.

## 3. Goals & Success Metrics
| Goal | Metric | Target |
|------|--------|--------|
| | | |

## 4. Stakeholders
| Name | Role | Responsibility |
|------|------|---------------|
| | | |

## 5. In Scope
- Item 1

## 6. Out of Scope
- Item 1

## 7. Functional Requirements
### FR-001: [Requirement Name]
**Description:** ...  
**Priority:** High / Medium / Low  
**Acceptance Criteria:**
- [ ] Criterion 1

## 8. Non-Functional Requirements
- Performance: ...
- Security: ...
- Availability: ...

## 9. Assumptions & Dependencies
- ...

## 10. Open Questions
| Question | Owner | Due |
|----------|-------|-----|
| | | |
`,
  "adr-template.md": `---
adr: "ADR-[NUMBER]"
title: "[Decision Title]"
date: YYYY-MM-DD
status: "Proposed | Accepted | Deprecated | Superseded"
deciders: []
---

# [ADR-NUMBER]: [Decision Title]

## Context
Describe the situation and forces that led to this decision.

## Decision
State the decision clearly in one or two sentences.

## Options Considered
### Option A: [Name]
**Pros:** ...  
**Cons:** ...

### Option B: [Name]
**Pros:** ...  
**Cons:** ...

## Consequences
### Positive
- ...

### Negative
- ...

## References
- [Link to relevant docs or discussions]
`,
  "runbook.md": `---
title: "[Service Name] Runbook"
version: 1.0
last_updated: YYYY-MM-DD
owner: ""
---

# [Service Name] — Runbook

## Overview
Brief description of the service and why this runbook exists.

## Prerequisites
- Access to: ...
- Tools required: ...

## Deployment

### Standard Deployment
\`\`\`bash
# Steps to deploy
\`\`\`

### Rollback Procedure
\`\`\`bash
# Steps to rollback
\`\`\`

## Health Checks
| Check | Expected | Command |
|-------|----------|---------|
| API health | 200 OK | \`curl /health\` |

## Incident Response

### Alert: [Alert Name]
**Severity:** High / Medium / Low  
**Symptoms:** ...  
**Investigation:**
1. Check logs: \`...\`
2. Check metrics: \`...\`

**Resolution:**
1. ...

## Contacts
| Role | Name | Contact |
|------|------|---------|
| On-call | | |
`,
};

export function generateDocTemplate(templateId: string, filename: string): string {
  const key = Object.keys(docTemplates).find((k) => k === filename || k.includes(templateId));
  return docTemplates[key ?? ""] ?? `# ${filename.replace(".md", "").replace(/-/g, " ")}\n\nTemplate content here.\n`;
}

// --------------- Obsidian Templates ---------------
export function generateObsidianNote(type: string, projectName: string): string {
  return `---
type: ${type}
project: ${projectName}
tags: [${type}, ${projectName}]
status: active
created: {{date}}
updated: {{date}}
---

# [${type.charAt(0).toUpperCase() + type.slice(1)} Name]

## Overview
Brief description.

## Details
...

## Related
- [[Link to related note]]

## Notes
...
`;
}

// --------------- File Tree Builder ---------------
export interface FileNode {
  name: string;
  type: "file" | "folder";
  children?: FileNode[];
  content?: string;
  path: string;
}

export function buildFileTree(config: ConfigState, selectedDefs: {
  skillDefs: any[];
  subagentDefs: any[];
  ruleDefs: any[];
  hookDefs: any[];
  docDefs: any[];
}): FileNode[] {
  const files: FileNode[] = [];

  if (config.core.includeClaudeMd) {
    files.push({ name: "CLAUDE.md", type: "file", path: "CLAUDE.md", content: generateClaudeMd(config) });
  }
  if (config.core.includeAgentsMd) {
    files.push({ name: "AGENTS.md", type: "file", path: "AGENTS.md", content: generateAgentsMd(config, selectedDefs.subagentDefs) });
  }
  files.push({ name: "README-SETUP.md", type: "file", path: "README-SETUP.md", content: generateReadmeSetup(config) });

  // .claude/ folder
  if (config.core.includeSettingsJson || config.core.includeRules || config.core.includeSkills || config.core.includeSubagents || config.core.includeHooks) {
    const claudeDir: FileNode = { name: ".claude", type: "folder", path: ".claude", children: [] };

    if (config.core.includeSettingsJson) {
      claudeDir.children!.push({ name: "settings.json", type: "file", path: ".claude/settings.json", content: generateSettingsJson(config, selectedDefs.hookDefs) });
    }

    if (config.core.includeRules && selectedDefs.ruleDefs.length > 0) {
      const rulesDir: FileNode = { name: "rules", type: "folder", path: ".claude/rules", children: [] };
      selectedDefs.ruleDefs.forEach((rule) => {
        rulesDir.children!.push({ name: rule.filename, type: "file", path: ".claude/rules/" + rule.filename, content: generateRuleContent(rule.id) });
      });
      claudeDir.children!.push(rulesDir);
    }

    if (config.core.includeSkills && selectedDefs.skillDefs.length > 0) {
      const skillsDir: FileNode = { name: "skills", type: "folder", path: ".claude/skills", children: [] };
      selectedDefs.skillDefs.forEach((skill) => {
        const skillPath = ".claude/skills/" + skill.id;
        const skillDir: FileNode = {
          name: skill.id,
          type: "folder",
          path: skillPath,
          children: [
            { name: "SKILL.md", type: "file", path: skillPath + "/SKILL.md", content: generateSkillMd(skill.id, skill.label) },
          ],
        };
        if (skill.templateFiles?.length > 0) {
          const tplPath = skillPath + "/templates";
          const templatesDir: FileNode = { name: "templates", type: "folder", path: tplPath, children: [] };
          skill.templateFiles.forEach((tf: string) => {
            templatesDir.children!.push({ name: tf, type: "file", path: tplPath + "/" + tf, content: "# " + tf.replace(".md", "").replace(/-/g, " ") + "\n\nTemplate content.\n" });
          });
          skillDir.children!.push(templatesDir);
        }
        skillsDir.children!.push(skillDir);
      });
      claudeDir.children!.push(skillsDir);
    }

    if (config.core.includeSubagents && selectedDefs.subagentDefs.length > 0) {
      const agentsDir: FileNode = { name: "agents", type: "folder", path: ".claude/agents", children: [] };
      selectedDefs.subagentDefs.forEach((agent) => {
        agentsDir.children!.push({ name: agent.id + ".md", type: "file", path: ".claude/agents/" + agent.id + ".md", content: generateSubagentMd(agent.id, agent) });
      });
      claudeDir.children!.push(agentsDir);
    }

    if (config.core.includeHooks && selectedDefs.hookDefs.length > 0) {
      const hooksDir: FileNode = { name: "hooks", type: "folder", path: ".claude/hooks", children: [] };
      selectedDefs.hookDefs.forEach((hook) => {
        hooksDir.children!.push({ name: hook.filename, type: "file", path: ".claude/hooks/" + hook.filename, content: generateHookScript(hook.filename) });
      });
      claudeDir.children!.push(hooksDir);
    }

    files.push(claudeDir);
  }

  // docs/ folder
  if (selectedDefs.docDefs.length > 0) {
    const docsDir: FileNode = { name: "docs", type: "folder", path: "docs", children: [] };
    const docFolders: Record<string, FileNode> = {};

    selectedDefs.docDefs.forEach((doc) => {
      const folder = doc.folder.replace("docs/", "");
      if (!docFolders[folder]) {
        docFolders[folder] = { name: folder, type: "folder", path: "docs/" + folder, children: [] };
        docsDir.children!.push(docFolders[folder]);
      }
      docFolders[folder].children!.push({
        name: doc.filename,
        type: "file",
        path: doc.folder + "/" + doc.filename,
        content: generateDocTemplate(doc.id, doc.filename),
      });
    });

    files.push(docsDir);
  }

  // obsidian-vault/
  if (config.obsidian.includeVault) {
    const vaultDir: FileNode = { name: "obsidian-vault", type: "folder", path: "obsidian-vault", children: [] };
    
    if (config.obsidian.includeTypedFolders) {
      config.obsidian.noteTaxonomy.forEach((type) => {
        const folderName = type.charAt(0).toUpperCase() + type.slice(1) + "s";
        const typeDir: FileNode = { name: folderName, type: "folder", path: "obsidian-vault/" + folderName, children: [] };
        
        if (config.obsidian.includeTemplateNotes) {
          typeDir.children!.push({
            name: "_template-" + type + ".md",
            type: "file",
            path: "obsidian-vault/" + folderName + "/_template-" + type + ".md",
            content: generateObsidianNote(type, config.basics.projectName),
          });
        }
        vaultDir.children!.push(typeDir);
      });
    }

    if (config.obsidian.includeCanvasStarter) {
      vaultDir.children!.push({
        name: "system-map.canvas",
        type: "file",
        path: "obsidian-vault/system-map.canvas",
        content: JSON.stringify({ nodes: [], edges: [] }, null, 2),
      });
    }

    files.push(vaultDir);
  }

  return files;
}

// Flatten file tree to a list of all file nodes for zip building
export function flattenTree(nodes: FileNode[], acc: FileNode[] = []): FileNode[] {
  for (const node of nodes) {
    if (node.type === "file") acc.push(node);
    if (node.children) flattenTree(node.children, acc);
  }
  return acc;
}
